"""첫 스키마 — 프로젝트 · 멤버 · 작업 · 안건 · 회의와 링크 둘

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-28

`web/src/types/domain.ts` 의 모양을 그대로 테이블로 옮긴 것이다.
배열(TaskLine · detail · memos · attendeeIds)은 JSONB 가 아니라 행으로 펴고 sort_order 를 둔다.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member")),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "meeting",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_meeting_project_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting")),
        sa.UniqueConstraint("seq", name=op.f("uq_meeting_seq")),
    )
    op.create_index("ix_meeting_project_id_date", "meeting", ["project_id", "date"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("start", sa.Date(), nullable=True),
        sa.Column("due", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint("priority in ('low', 'normal', 'high')", name=op.f("ck_task_priority")),
        sa.CheckConstraint(
            "status in ('todo', 'doing', 'blocked', 'done')", name=op.f("ck_task_status")
        ),
        sa.CheckConstraint(
            "parent_id is null or parent_id <> id", name=op.f("ck_task_parent_not_self")
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["member.id"], name=op.f("fk_task_owner_id")),
        sa.ForeignKeyConstraint(["parent_id"], ["task.id"], name=op.f("fk_task_parent_id")),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_task_project_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        sa.UniqueConstraint("project_id", "key", name=op.f("uq_task_project_id_key")),
        sa.UniqueConstraint("seq", name=op.f("uq_task_seq")),
    )
    op.create_index("ix_task_parent_id", "task", ["parent_id"], unique=False)
    op.create_index("ix_task_project_id_status", "task", ["project_id", "status"], unique=False)
    op.create_table(
        "thread",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("parent_thread_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint("state in ('queued', 'open', 'decided')", name=op.f("ck_thread_state")),
        sa.ForeignKeyConstraint(["owner_id"], ["member.id"], name=op.f("fk_thread_owner_id")),
        sa.ForeignKeyConstraint(
            ["parent_thread_id"], ["thread.id"], name=op.f("fk_thread_parent_thread_id")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_thread_project_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread")),
        sa.UniqueConstraint("seq", name=op.f("uq_thread_seq")),
    )
    op.create_index("ix_thread_project_id", "thread", ["project_id"], unique=False)
    op.create_table(
        "entry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "kind in ('raise', 'defer', 'decide', 'refine', 'change', 'split')",
            name=op.f("ck_entry_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["meeting.id"], name=op.f("fk_entry_meeting_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["member.id"], name=op.f("fk_entry_owner_id")),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["thread.id"], name=op.f("fk_entry_thread_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry")),
        sa.UniqueConstraint("seq", name=op.f("uq_entry_seq")),
    )
    op.create_index("ix_entry_meeting_id", "entry", ["meeting_id"], unique=False)
    op.create_index(
        "ix_entry_thread_id_created_at", "entry", ["thread_id", "created_at"], unique=False
    )
    op.create_table(
        "meeting_attendee",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
            name=op.f("fk_meeting_attendee_meeting_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
            name=op.f("fk_meeting_attendee_member_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meeting_id", "member_id", name=op.f("pk_meeting_attendee")),
    )
    op.create_table(
        "meeting_memo",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("promoted_thread_id", sa.String(length=36), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
            name=op.f("fk_meeting_memo_meeting_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["promoted_thread_id"], ["thread.id"], name=op.f("fk_meeting_memo_promoted_thread_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_memo")),
    )
    op.create_table(
        "meeting_task_link",
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
            name=op.f("fk_meeting_task_link_meeting_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_meeting_task_link_task_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("meeting_id", "task_id", name=op.f("pk_meeting_task_link")),
    )
    op.create_table(
        "task_line",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind in ('check', 'bullet')", name=op.f("ck_task_line_kind")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_task_line_task_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_line")),
    )
    op.create_table(
        "task_thread_link",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_task_thread_link_task_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
            name=op.f("fk_task_thread_link_thread_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", "thread_id", name=op.f("pk_task_thread_link")),
    )
    op.create_table(
        "entry_detail",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("fk_entry_detail_entry_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry_detail")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_detail")
    op.drop_table("task_thread_link")
    op.drop_table("task_line")
    op.drop_table("meeting_task_link")
    op.drop_table("meeting_memo")
    op.drop_table("meeting_attendee")
    op.drop_index("ix_entry_thread_id_created_at", table_name="entry")
    op.drop_index("ix_entry_meeting_id", table_name="entry")
    op.drop_table("entry")
    op.drop_index("ix_thread_project_id", table_name="thread")
    op.drop_table("thread")
    op.drop_index("ix_task_project_id_status", table_name="task")
    op.drop_index("ix_task_parent_id", table_name="task")
    op.drop_table("task")
    op.drop_index("ix_meeting_project_id_date", table_name="meeting")
    op.drop_table("meeting")
    op.drop_table("project")
    op.drop_table("member")
    # ### end Alembic commands ###
